[package]
name = "headers"
version = "0.1.0"
edition = "2021"

[dependencies]
error-chain = "0.12.4"
console = "0.15.8"
tokio = { version = "1.41.1", features = ["rt", "rt-multi-thread", "macros"] }
reqwest = "0.12.9"
